# Generated by Django 3.2.9 on 2021-11-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Nazwa użytkownika')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email służbowy')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('position', models.CharField(max_length=50, verbose_name='Stanowisko')),
                ('position_addinfo', models.CharField(blank=True, max_length=50, verbose_name='Dopisek "sprz."')),
                ('workplace', models.CharField(blank=True, max_length=50, verbose_name='Dział/Filia')),
                ('role', models.CharField(choices=[('P', 'Nie'), ('K', 'Kierownik - przełożony'), ('T', 'Instruktor, Zastępca Dyrektora'), ('S', 'Dyrektor')], max_length=10, null=True, verbose_name='Stanowisko kierownicze')),
                ('working_hours', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Wymiar etatu')),
                ('annual_leave', models.IntegerField(default=26, verbose_name='Roczny wymiar urlopu')),
                ('current_leave', models.IntegerField(default=0, verbose_name='Urlop (pozostało)')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Umowa do:')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_superuser', models.BooleanField(default=False)),
                ('additional_info', models.CharField(blank=True, max_length=100, verbose_name='Dodatkowe informacje')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
